[package]
name = "zip_utils"
version = "0.1.0"
authors = ["Fabrice Desr√© <fabrice@desre.org>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
base64 = "0.13"
zip = "0.5"
ring = "0.16"
simple_asn1 = "0.6.1"
chrono = "0.4"
x509-signature = "0.5"
hex-slice = "0.1.4"
