[package]
name = "hawk"
version = "3.2.2"
authors = ["Jonas Finnemann Jensen <jopsen@gmail.com>", "Dustin J. Mitchell <dustin@mozilla.com>"]
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/taskcluster/rust-hawk"
documentation = "https://docs.rs/hawk/"
homepage = "https://docs.rs/hawk/"
description = "Hawk Implementation for Rust"
edition = "2018"
build = "build.rs"
exclude = [
    "docker/*",
    ".taskcluster.yml",
    ".git*",
]

[dev-dependencies]
pretty_assertions = "^0.7.1"

[features]
default = ["use_ring"]
use_ring = ["ring"]
use_openssl = ["openssl"]

[dependencies]
base64 = "0.13"
ring = { version = "0.16.0", optional = true }
openssl = { version = "0.10.20", optional = true }
url = "2.1"
thiserror = "1.0"
anyhow = "1.0"
once_cell = "1.4"
log = "0.4"
