[package]
authors = ["Fabrice Desr√© <fabrice@desre.org>"]
edition = "2018"
license = "AGPL-3.0-only"
name = "costaeres"
version = "0.1.1"

[dependencies]
actix-rt = "2.6"
actix-web = {version = "4.0"}
async-std = {version = "1.10", features = ["attributes"]}
async-trait = "0.1"
base64 = "0.13"
chrono = {version = "0.4", features = ["serde"]}
futures = "0.3"
futures-core = "0.3"
lazy_static = "1.4"
libsqlite3-sys = "0.24"
log = "0.4"
lru = "0.6"
mime_guess = "2.0"
parking_lot = "0.12"
pin-project-lite = "0.2.7"
secular = "1.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
speedy = "*"
sqlx = {git = "https://github.com/fabricedesre/sqlx.git", branch = "update-libsqlite3-sys", features = ["runtime-async-std-rustls", "migrate", "sqlite", "chrono"]}
thiserror = "1.0"
toml = "0.5"
uuid = {version = "0.8", features = ["v4"]}

[dev-dependencies]
env_logger = "0.8"
