name: Coverage

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  grcov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build and test sources
        run: |
          cargo build;
          cargo test;
        env:
          CARGO_INCREMENTAL: '0'
          RUSTC_BOOTSTRAP: '1'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off'
      - name: Collect hit files, install grcov and create coveralls report
        run: |
          zip -0 ccov.zip `find . \( -name "test_serv*.gc*" \) -print`;
          cargo install grcov;
          grcov ccov.zip -s . -t coveralls --llvm --branch --ignore-not-existing --ignore "/*" --token ${{ secrets.CODECOV_TOKEN }} > coveralls.json
      - uses: codecov/codecov-action@v1
        with:
          file: ./coveralls.json
          fail_ci_if_error: true
